remove mentions of "harness" - switch to ad-hoc image terminology in code
docs will be updated in upcoming PRs since links will need to be renamed in other repos

diff --git a/assets/tests/ocp-tests-runner.template b/assets/tests/ocp-tests-runner.template
--- a/assets/tests/ocp-tests-runner.template
+++ b/assets/tests/ocp-tests-runner.template
@@ -12,7 +12,7 @@ spec:
     spec:
       serviceAccount: {{.ServiceAccount}}
       containers:
-      - name: test-harness
+      - name: test-container
         image: {{.Image}}
         imagePullPolicy: Always
         command: [ /bin/sh, /test-cmd/test-cmd.sh ]
@@ -64,7 +64,7 @@ cat <<PUSH_RESULTS > push-results.sh
 
 JOB_POD=\$(oc get pods -l job-name={{.JobName}} -o=jsonpath='{.items[0].metadata.name}')
 echo "Found Job Pod: \$JOB_POD"
-while ! oc get pod \$JOB_POD -o jsonpath='{.status.containerStatuses[?(@.name=="test-harness")].state}' | grep -q terminated; do sleep 1; done
+while ! oc get pod \$JOB_POD -o jsonpath='{.status.containerStatuses[?(@.name=="test-container")].state}' | grep -q terminated; do sleep 1; done
 for i in {1..5}; do oc rsync {{.OutputDir}}/. $(hostname):{{.OutputDir}} && break; sleep 10; done
 PUSH_RESULTS
 
@@ -87,10 +87,10 @@ mkdir -p "{{.OutputDir}}/containerLogs"
 JOB_POD=$(oc get pods -l job-name={{.JobName}} -o=jsonpath='{.items[0].metadata.name}')
 
 if [[ ! $JOB_POD ]]; then
-  echo "test harness pod not found, may have been terminated. exiting"
+  echo "test pod not found, may have been terminated. exiting"
 
 else
-  echo "found test harness pod $JOB_POD"
-  oc logs $JOB_POD -c test-harness > "{{.OutputDir}}/containerLogs/${JOB_POD}-test-harness.log"
+  echo "found test pod $JOB_POD"
+  oc logs $JOB_POD -c test-container > "{{.OutputDir}}/containerLogs/${JOB_POD}-test-adHocTestImage.log"
   oc logs $JOB_POD -c push-results > "{{.OutputDir}}/containerLogs/${JOB_POD}-push-results.log"
 fi
